name: golf
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.8    # Python version 3.8
    - geopandas     # Geospatial extension of pandas
    - matplotlib    # 2D plotting library
    - numpy         # N-d array and numerics 
    - pandas        # Labeled data analysis
    - spyder        # Scientific development environment
    - shapely       # Vector formats
    - census        # Census data access
    - osmnx         # OSM data access
    - selenium      # Web scraping
    - scipy         # Common math/stats/science functions
    - routingpy     # Routing tools